inherit_from: .rubocop_todo.yml

inherit_gem:
  rubocop-discourse: default.yml

AllCops:
  TargetRubyVersion: 3.2
  NewCops: disable
  Exclude:
    - lib/generators/snapcher/templates/install.rb
    - sample-app/bin/bundle

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
