source "https://rubygems.org"

ruby "3.2.2"

gem "jbuilder"
gem "puma", ">= 5.0"
gem "rails", "~> 7.1.1"
gem "sprockets-rails"
gem "sqlite3", "~> 1.4"

gem "snapcher", path: "../"

gem "bootsnap", require: false
gem "tzinfo-data", platforms: %i[windows jruby]

group :development, :test do
  gem "debug", platforms: %i[mri windows]
end

group :development do
  gem "web-console"
end
